// 成就
export const ACHIEVEMENTS = [
  { id: 'first_brick', name: '物勒工名', icon: '砖', desc: '在中华门读到第一块城砖铭文' },
  { id: 'all_bricks', name: '一砖一名', icon: '铭', desc: '读遍序章里所有的城砖铭文' },
  { id: 'brick_perfect', name: '火眼金睛', icon: '验', desc: '验砖时一块也没有判错' },
  { id: 'kiln_perfect', name: '炉火纯青', icon: '火', desc: '烧出一窑「无瑕」的青砖' },
  { id: 'emperor', name: '鞋拔子脸？', icon: '龙', desc: '认出了微服的「老员外」', secret: true },
  { id: 'bookworm_perfect', name: '芸香满架', icon: '芸', desc: '捉蠹时一个字也没被啃掉' },
  { id: 'couplets', name: '妙对', icon: '对', desc: '和解缙对对子，全部对上' },
  { id: 'books_perfect', name: '四部归位', icon: '书', desc: '经史子集，全部归架正确' },
  { id: 'star_perfect', name: '牵星过洋', icon: '星', desc: '一次不错地走完整条针路' },
  { id: 'giraffe', name: '瑞应麒麟', icon: '麟', desc: '喂「麒麟」吃到了它最爱的东西' },
  { id: 'tiles_perfect', name: '琉璃无瑕', icon: '瓦', desc: '转瓦三关全部拿到无瑕' },
  { id: 'lamps', name: '长明', icon: '灯', desc: '点亮琉璃塔上的长明灯' },
  { id: 'qingmei', name: '青梅竹马', icon: '梅', desc: '在长干里遇见一对小冤家', secret: true },
  { id: 'riddles_all', name: '打虎英雄', icon: '谜', desc: '猜中秦淮灯会上全部的灯谜' },
  { id: 'mudan', name: '物归原主', icon: '情', desc: '把一句词「还」给了汤显祖', secret: true },
  { id: 'wanli', name: '无事可记', icon: '历', desc: '在万历十五年，说出那句感慨', secret: true },
  { id: 'carve_perfect', name: '反书', icon: '刻', desc: '刻版时一字不错' },
  { id: 'codex_half', name: '博闻', icon: '博', desc: '金陵志收录过半' },
  { id: 'codex_all', name: '金陵通', icon: '通', desc: '金陵志全部收录' },
  { id: 'nishang', name: '霓裳', icon: '裳', desc: '见到康晔的霓裳之姿', secret: true },
  { id: 'quiz_perfect', name: '心灯不灭', icon: '心', desc: '问史一战，一盏心灯也没熄' },
  { id: 'clear', name: '寻踪人', icon: '踪', desc: '走完《金陵寻踪》的旅程' },
  { id: 'qilin_pat', name: '摸摸头', icon: '麒', desc: '在尾声里，再摸一次石麒麟的头', secret: true },
];
