// 终章「问史」题库：每题都对应《金陵志》里的一条（codex），答案就写在那一条里。
// { id, codex, chapter, q, options: [4], answer: 正确选项下标, explain: ≤60 字, level: 1 易 / 2 中 / 3 难 }
// chapter 与 codex 条目的章节一致（0 序章 … 5 万历，6 终章）。小游戏会自行打乱选项顺序。
export const QUESTIONS = [
  // ---------------------------------------------------------------- 序章 · 通用
  { id: 'q_zhm_name', codex: 'zhonghuamen', chapter: 0, level: 1,
    q: '中华门在明代叫什么名字？',
    options: ['聚宝门', '通济门', '正阳门', '石城门'], answer: 0,
    explain: '中华门明代称聚宝门，1931年才改名中华门。' },
  { id: 'q_cbd_count', codex: 'cangbingdong', chapter: 0, level: 2,
    q: '中华门一共有多少个藏兵洞？',
    options: ['13个', '27个', '36个', '72个'], answer: 1,
    explain: '瓮城上下13个，两侧马道下14个，共27个，据说可藏兵三千。' },
  { id: 'q_wall_1318', codex: 'city_wall', chapter: 0, level: 1,
    q: '老南京说的“里十三，外十八”指的是什么？',
    options: ['城墙的高与宽', '城砖的长与重', '京城与外郭的城门数', '瓮城与藏兵洞数'], answer: 2,
    explain: '京城设城门13座，外郭另有18座。' },
  { id: 'q_brick_names', codex: 'brick_inscription', chapter: 0, level: 1,
    q: '城砖铭文层层署名，最基层签名的是谁？',
    options: ['工部尚书', '城门守将', '应天知府', '窑匠和造砖人夫'], answer: 3,
    explain: '从府县提调官一路签到窑匠和造砖人夫，最多达十一级。' },
  { id: 'q_xiaoling', codex: 'xiaoling', chapter: 0, level: 1,
    q: '明孝陵是谁的陵墓？',
    options: ['朱棣与徐皇后', '朱元璋与马皇后', '朱标与常氏', '朱瞻基与孙皇后'], answer: 1,
    explain: '明孝陵是明太祖朱元璋与马皇后的合葬陵。' },
  { id: 'q_shixianglu', codex: 'aling', chapter: 0, level: 2,
    q: '明孝陵石象路两旁共有几种石兽？',
    options: ['四种', '六种', '八种', '十二种'], answer: 1,
    explain: '狮子、獬豸、骆驼、象、麒麟、马，每种两对，共十二对。' },
  { id: 'q_du_yiyu', codex: 'du', chapter: 0, level: 1,
    q: '啃书的“蠹鱼”又叫什么？',
    options: ['衣鱼', '蜉蝣', '螟蛉', '蝼蛄'], answer: 0,
    explain: '蠹鱼也叫衣鱼、白鱼，专啃纸张和浆糊里的淀粉。' },
  { id: 'q_du_wudu', codex: 'du', chapter: 0, level: 2,
    q: '韩非把危害国家的人比作蛀虫，写了哪篇文章？',
    options: ['《说难》', '《孤愤》', '《五蠹》', '《显学》'], answer: 2,
    explain: '韩非《五蠹》：借“蠹”比喻从内部蛀空国家的人。' },
  { id: 'q_ye_char', codex: 'kangye', chapter: 0, level: 1,
    q: '康晔的“晔”字，由哪两部分组成？',
    options: ['日和月', '火和华', '日和叶', '日和华'], answer: 3,
    explain: '“晔”左日右华，《说文》释为“光也”；日月并肩则为“明”。' },

  // ---------------------------------------------------------------- 第一章 · 洪武 聚宝门
  { id: 'q_zyz_birth', codex: 'zhu_yuanzhang', chapter: 1, level: 2,
    q: '朱元璋出生在哪里？',
    options: ['应天府', '濠州钟离', '开封府', '苏州府'], answer: 1,
    explain: '朱元璋生于濠州钟离，即今安徽凤阳，本名重八。' },
  { id: 'q_zyz_zhusheng', codex: 'zhu_yuanzhang', chapter: 1, level: 2,
    q: '“高筑墙，广积粮，缓称王”是谁献给朱元璋的计策？',
    options: ['刘基', '李善长', '朱升', '徐达'], answer: 2,
    explain: '谋士朱升献策，“高筑墙”成了南京城墙的起点。' },
  { id: 'q_ma_bing', codex: 'empress_ma', chapter: 1, level: 1,
    q: '马皇后揣在怀里、偷偷送给朱元璋的是什么？',
    options: ['刚出锅的炊饼', '粽子', '烤红薯', '米糕'], answer: 0,
    explain: '她把刚出锅的炊饼揣在怀里送去，胸口都被烫焦了。' },
  { id: 'q_wlgm_le', codex: 'wulegongming', chapter: 1, level: 1,
    q: '“物勒工名”中的“勒”是什么意思？',
    options: ['捆绑', '刻', '勒索', '拉紧'], answer: 1,
    explain: '勒就是刻：器物上刻工匠之名，“以考其诚”。' },
  { id: 'q_nuomi', codex: 'nuomi_mortar', chapter: 1, level: 2,
    q: '糯米灰浆格外坚韧，主要归功于糯米中的什么？',
    options: ['蛋白质', '植物油', '糖分', '支链淀粉'], answer: 3,
    explain: '支链淀粉调控碳酸钙晶体生长，形成致密的复合结构。' },
  { id: 'q_shenxiu', codex: 'jubaopen', chapter: 1, level: 2,
    q: '据《明史》，出钱助筑都城三分之一的吴兴富民叫什么？',
    options: ['胡雪岩', '沈秀', '石崇', '邓通'], answer: 1,
    explain: '《明史》记为沈秀，一般认为就是传说中的沈万三。' },
  { id: 'q_qingzhuan', codex: 'qingzhuan', chapter: 1, level: 2,
    q: '城砖出窑前，为什么会由红转青？',
    options: ['刷了一层青漆', '窑顶浇水、隔绝空气', '用松烟熏黑', '泡进河里冷却'], answer: 1,
    explain: '窨水隔绝空气，黏土里的铁被还原成青黑色的低价铁。' },
  { id: 'q_yingtian', codex: 'yingtian', chapter: 1, level: 1,
    q: '1356年朱元璋攻下集庆，把它改名为什么？',
    options: ['顺天府', '奉天府', '承天府', '应天府'], answer: 3,
    explain: '取“顺应天命”之意，改集庆路为应天府。' },
  { id: 'q_chunlian', codex: 'chunlian', chapter: 1, level: 1,
    q: '相传是哪位皇帝下旨，让家家户户贴春联？',
    options: ['宋太祖赵匡胤', '唐太宗李世民', '明太祖朱元璋', '清圣祖玄烨'], answer: 2,
    explain: '据《簪云楼杂说》，朱元璋下旨贴春联，还微服出宫看热闹。' },

  // ---------------------------------------------------------------- 第二章 · 永乐 文渊阁
  { id: 'q_dadian_juan', codex: 'yongle_dadian', chapter: 2, level: 1,
    q: '《永乐大典》正文大约有多少卷？',
    options: ['两百多卷', '两千多卷', '两万两千多卷', '二十万卷'], answer: 2,
    explain: '正文22877卷，凡例目录60卷，约3.7亿字。' },
  { id: 'q_dadian_left', codex: 'yongle_dadian', chapter: 2, level: 2,
    q: '今天存世的《永乐大典》大约还有多少？',
    options: ['四百余册', '全部完好', '一万余册', '仅剩一册'], answer: 0,
    explain: '存世的嘉靖副本仅四百余册，不到原书的百分之四。' },
  { id: 'q_zhengyun', codex: 'hongwu_zhengyun', chapter: 2, level: 2,
    q: '《永乐大典》是按照哪部韵书来编排的？',
    options: ['《广韵》', '《洪武正韵》', '《切韵》', '《中原音韵》'], answer: 1,
    explain: '以《洪武正韵》为纲：“用韵以统字，用字以系事”。' },
  { id: 'q_seed', codex: 'yao_guangxiao', chapter: 2, level: 1,
    q: '姚广孝劝朱棣不要杀方孝孺，理由是什么？',
    options: ['他答应了投降', '他会写诏书', '他是皇亲国戚', '杀了他读书种子就绝了'], answer: 3,
    explain: '“杀孝孺，天下读书种子绝矣。”' },
  { id: 'q_fang_edict', codex: 'fang_xiaoru', chapter: 2, level: 1,
    q: '方孝孺宁死不肯为朱棣起草什么？',
    options: ['即位诏书', '讨元檄文', '大典序言', '出海敕书'], answer: 0,
    explain: '他掷笔于地：“死即死耳，诏不可草。”' },
  { id: 'q_neige', codex: 'wenyuange', chapter: 2, level: 1,
    q: '明代“内阁”的由来，和哪座建筑有关？',
    options: ['天一阁', '滕王阁', '文渊阁', '凌烟阁'], answer: 2,
    explain: '永乐初年七位翰林官入直文渊阁参与机务，是内阁的开端。' },
  { id: 'q_jibu', codex: 'jingshiziji', chapter: 2, level: 2,
    q: '四部分类法中，诗文词曲归入哪一部？',
    options: ['经部', '史部', '子部', '集部'], answer: 3,
    explain: '经收儒家经典，史收史书，子收诸子百家，集收诗文词曲。' },
  { id: 'q_yun', codex: 'yunxiang', chapter: 2, level: 1,
    q: '古人藏书用来辟蠹、还让“芸阁”成了藏书处雅称的香草是？',
    options: ['艾草', '芸草', '菖蒲', '薄荷'], answer: 1,
    explain: '沈括说：“古人藏书辟蠹用芸。”' },
  { id: 'q_shendu', codex: 'shen_du', chapter: 2, level: 1,
    q: '相传明成祖称沈度为“我朝”的哪一位书法家？',
    options: ['王羲之', '颜真卿', '柳公权', '赵孟頫'], answer: 0,
    explain: '相传成祖称他“我朝王羲之”；他的小楷是台阁体的典范。' },

  // ---------------------------------------------------------------- 第三章 · 永乐 龙江宝船厂
  { id: 'q_zh_surname', codex: 'zheng_he', chapter: 3, level: 1,
    q: '郑和原本姓什么？',
    options: ['郑', '王', '马', '洪'], answer: 2,
    explain: '郑和本姓马，小名三保，永乐二年被赐姓“郑”。' },
  { id: 'q_zh_day', codex: 'zheng_he', chapter: 3, level: 2,
    q: '每年7月11日的“中国航海日”，纪念的是什么？',
    options: ['郑和首次下西洋', '宝船厂建成', '郑和的生日', '航海图刊行'], answer: 0,
    explain: '中国航海日纪念郑和首次扬帆出海。' },
  { id: 'q_xiu', codex: 'treasure_ship', chapter: 3, level: 2,
    q: '《明史》说宝船“修四十四丈”，“修”是什么意思？',
    options: ['宽', '长', '高', '修理'], answer: 1,
    explain: '“修”是长，“广”是宽：长四十四丈、宽十八丈。' },
  { id: 'q_zuotang', codex: 'longjiang_shipyard', chapter: 3, level: 1,
    q: '宝船厂里用来造船的长条形船坞，叫什么？',
    options: ['水寨', '船台', '码头', '作塘'], answer: 3,
    explain: '船在作塘中造好，引江水入塘，浮起后驶入长江。' },
  { id: 'q_qianxing', codex: 'qianxingban', chapter: 3, level: 1,
    q: '牵星板主要用来测量什么？',
    options: ['海水的深度', '风力的大小', '星辰离海平线的高度', '船行的速度'], answer: 2,
    explain: '量出北辰星等星辰的高度，就能推算船的南北位置。' },
  { id: 'q_24xiang', codex: 'zhenlu', chapter: 3, level: 2,
    q: '明代罗盘把一周分成多少个“单针”方向？',
    options: ['八个', '二十四个', '十二个', '三十六个'], answer: 1,
    explain: '十二地支、八天干、四卦，共二十四向，每向十五度。' },
  { id: 'q_giraffe', codex: 'giraffe_qilin', chapter: 3, level: 1,
    q: '1414年被当作“麒麟”进献的动物，其实是什么？',
    options: ['斑马', '犀牛', '羚羊', '长颈鹿'], answer: 3,
    explain: '榜葛剌国献上的长颈鹿，被视为仁兽麒麟。' },
  { id: 'q_mahuan', codex: 'ma_huan', chapter: 3, level: 3,
    q: '马欢把随郑和下西洋的见闻，写成了哪本书？',
    options: ['《瀛涯胜览》', '《星槎胜览》', '《西洋番国志》', '《岛夷志略》'], answer: 0,
    explain: '《瀛涯胜览》记下沿途二十国风物，1451年定稿。' },
  { id: 'q_jinghai', codex: 'tianfei_jinghai', chapter: 3, level: 2,
    q: '1842年《南京条约》的议约谈判，在哪座寺里进行？',
    options: ['鸡鸣寺', '静海寺', '栖霞寺', '灵谷寺'], answer: 1,
    explain: '为褒奖郑和远航而建的静海寺，也见证了近代的屈辱。' },

  // ---------------------------------------------------------------- 第四章 · 宣德 大报恩寺琉璃塔
  { id: 'q_tower_floors', codex: 'porcelain_tower', chapter: 4, level: 1,
    q: '大报恩寺琉璃塔有几层几面？',
    options: ['七层六面', '十三层四面', '九层八面', '五层八面'], answer: 2,
    explain: '九层八面，高约78米，被誉为“天下第一塔”。' },
  { id: 'q_lamps146', codex: 'changming_lamps', chapter: 4, level: 2,
    q: '据记载，琉璃塔九层内外共设灯多少盏？',
    options: ['一百四十六盏', '七十二盏', '一百零八盏', '三百六十盏'], answer: 0,
    explain: '共设篝灯一百四十六盏，一昼夜耗油六十四斤有余。' },
  { id: 'q_three_sets', codex: 'glazed_parts', chapter: 4, level: 2,
    q: '张岱说琉璃构件“一式三份”，另外两份怎么处理？',
    options: ['送给外国使节', '砸碎重烧', '拿去修城墙', '编号埋入地下备用'], answer: 3,
    explain: '“成其一，埋其二，编号识之。”1958年果真挖出了库房。' },
  { id: 'q_qingmei', codex: 'changganli', chapter: 4, level: 1,
    q: '成语“青梅竹马”出自李白的哪首诗？',
    options: ['《静夜思》', '《将进酒》', '《长干行》', '《登金陵凤凰台》'], answer: 2,
    explain: '“同居长干里，两小无嫌猜”——也出自《长干行》。' },
  { id: 'q_ashoka', codex: 'ashoka_pagoda', chapter: 4, level: 2,
    q: '2008年长干寺地宫出土、供奉佛顶真骨的宝塔叫什么？',
    options: ['雷峰塔', '七宝阿育王塔', '大雁塔', '释迦塔'], answer: 1,
    explain: '七宝阿育王塔高约1.2米，是出土体量最大的阿育王塔。' },
  { id: 'q_jubaoshan', codex: 'jubaoshan_kiln', chapter: 4, level: 1,
    q: '明代烧造琉璃的聚宝山，就是今天南京的哪里？',
    options: ['雨花台', '紫金山', '清凉山', '牛首山'], answer: 0,
    explain: '聚宝山即今雨花台一带，相传因“落花如雨”得名。' },
  { id: 'q_xuande_edict', codex: 'xuande', chapter: 4, level: 2,
    q: '宣德三年下敕、催大报恩寺限期完工的是哪位皇帝？',
    options: ['明太祖', '明成祖', '明神宗', '明宣宗'], answer: 3,
    explain: '明宣宗朱瞻基下敕给郑和等人，限当年八月前完工。' },
  { id: 'q_cuzhi', codex: 'xuande', chapter: 4, level: 1,
    q: '明宣宗有什么爱好，被民间戏称“促织天子”？',
    options: ['放风筝', '斗鸡', '斗蟋蟀', '养鹦鹉'], answer: 2,
    explain: '促织就是蟋蟀；蒲松龄《促织》写的正是宣德年间。' },

  // ---------------------------------------------------------------- 第五章 · 万历十五年 秦淮
  { id: 'q_hairui_coffin', codex: 'hai_rui', chapter: 5, level: 1,
    q: '海瑞上《治安疏》之前，先做了什么准备？',
    options: ['买好一口棺材', '辞官回乡', '写好遗诗', '逃往海南'], answer: 0,
    explain: '他买好棺材、与妻儿诀别，然后直言进谏。' },
  { id: 'q_hairui_post', codex: 'hai_rui', chapter: 5, level: 2,
    q: '万历十五年海瑞去世时，官居何职？',
    options: ['内阁首辅', '南京右都御史', '吏部尚书', '应天巡抚'], answer: 1,
    explain: '七十多岁被召回南京，官至南京右都御史，死于任上。' },
  { id: 'q_zichai', codex: 'tang_xianzu', chapter: 5, level: 3,
    q: '汤显祖约在1587年前后，在南京改写完成的剧作是？',
    options: ['《牡丹亭》', '《桃花扇》', '《长生殿》', '《紫钗记》'], answer: 3,
    explain: '《紫钗记》是“临川四梦”之一；《牡丹亭》成于1598年。' },
  { id: 'q_1616', codex: 'tang_xianzu', chapter: 5, level: 1,
    q: '汤显祖与哪位西方剧作家，同在1616年去世？',
    options: ['莫里哀', '莎士比亚', '歌德', '易卜生'], answer: 1,
    explain: '东西方两位戏剧大家，同在1616年辞世。' },
  { id: 'q_wanli15', codex: 'wanli15', chapter: 5, level: 1,
    q: '以“万历十五年”为书名写书的历史学家是谁？',
    options: ['钱穆', '吴晗', '黄仁宇', '陈寅恪'], answer: 2,
    explain: '黄仁宇的《万历十五年》，英文版1981年出版。' },
  { id: 'q_mingyuan', codex: 'gongyuan', chapter: 5, level: 1,
    q: '江南贡院里，考官登高俯瞰全场的楼叫什么？',
    options: ['黄鹤楼', '明远楼', '阅江楼', '岳阳楼'], answer: 1,
    explain: '明远楼建于嘉靖十三年（1534），考官在楼上监临。' },
  { id: 'q_qianzi', codex: 'qianziwen', chapter: 5, level: 1,
    q: '江南贡院的号舍，用哪部书里的字来编号？',
    options: ['《百家姓》', '《三字经》', '《论语》', '《千字文》'], answer: 3,
    explain: '每条号巷一个千字文的字，巷内再按一、二、三排号。' },
  { id: 'q_panchi', codex: 'fuzimiao', chapter: 5, level: 1,
    q: '夫子庙前的泮池，其实是哪条河的一段？',
    options: ['秦淮河', '长江', '金川河', '运河'], answer: 0,
    explain: '借用一段秦淮河为泮池，据说全国文庙仅此一例。' },
  { id: 'q_xiyouji', codex: 'shidetang', chapter: 5, level: 2,
    q: '现存最早的完整本《西游记》，是哪家书坊刻印的？',
    options: ['苏州汲古阁', '金陵世德堂', '建阳余氏', '北京琉璃厂'], answer: 1,
    explain: '世德堂本刻于万历二十年（1592），全名《新刻出像官板大字西游记》。' },
  { id: 'q_wuyi', codex: 'wuyixiang', chapter: 5, level: 1,
    q: '“旧时王谢堂前燕，飞入寻常百姓家”是谁的诗？',
    options: ['杜牧', '李白', '白居易', '刘禹锡'], answer: 3,
    explain: '刘禹锡《乌衣巷》，写的就是秦淮河南岸的乌衣巷。' },
  { id: 'q_fenyue', codex: 'wende_bridge', chapter: 5, level: 2,
    q: '“文德分月”要在什么时候才能看到？',
    options: ['正月十五元宵', '农历十一月十五子夜', '八月十五中秋', '七月初七七夕'], answer: 1,
    explain: '冬月十五子夜，桥影恰好把水中的月影分成两半。' },
  { id: 'q_lantern10', codex: 'qinhuai_lanterns', chapter: 5, level: 2,
    q: '永乐七年，明成祖规定元宵节给百官放假几天？',
    options: ['一天', '三天', '十天', '一个月'], answer: 2,
    explain: '元宵节从正月十一起放假十天，“上元十夜灯”盛极一时。' },

  // ---------------------------------------------------------------- 终章 · 通用
  { id: 'q_ming16', codex: 'ming_dynasty', chapter: 6, level: 2,
    q: '明朝一共历经多少位皇帝？',
    options: ['十二位', '十四位', '十六位', '二十位'], answer: 2,
    explain: '1368年至1644年，前后276年，历十六帝。' },
  { id: 'q_mudan', codex: 'mudan_line', chapter: 6, level: 1,
    q: '“情不知所起，一往而深”出自哪部作品的题词？',
    options: ['《西厢记》', '《牡丹亭》', '《桃花扇》', '《长生殿》'], answer: 1,
    explain: '汤显祖《牡丹亭记题词》：“生者可以死，死可以生。”' },
  { id: 'q_wall1386', codex: 'wall_completed', chapter: 6, level: 2,
    q: '京城城墙的主体，大约在哪一年前后完工？',
    options: ['洪武十九年（1386）', '永乐十九年（1421）', '宣德三年（1428）', '万历十五年（1587）'], answer: 0,
    explain: '从1366年算起约二十年；外郭等工程延续到1393年。' },
  { id: 'q_maiwang', codex: 'maiwang', chapter: 6, level: 2,
    q: '传说蠹鱼吃了哪两个字三次，就会化为“脉望”？',
    options: ['富贵', '天地', '神仙', '日月'], answer: 2,
    explain: '《酉阳杂俎》：“蠹鱼三食神仙字，则化为此物。”' },
];
